version: '3'

services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    restart: always
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - default
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"

  etcd:
    image: 'quay.io/coreos/etcd:v3.5.5'
    container_name: etcd
    restart: always
    ports:
      - 2379:2379
    networks:
      - default
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCDCTL_API=3

  fileserver:
    image: 'golang:alpine'
    container_name: fileserver
    restart: always
    volumes:
      - ./cmd/publish/public/video:/public/video
      - ./cmd/publish/public/cover:/public/cover
      - ./pkg/fileserver/main.go:/prog/main.go
    ports:
      - 8000:8000
    networks:
      - default
    command: 'go run /prog/main.go'

  jaeger:
    image: 'jaegertracing/all-in-one:latest'
    container_name: jaeger
    restart: always
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - default
